### ISSUE TITLE
tilecache.js leaks memory

### ISSUE THREAD

**Issue by sethfitz** [hanchao/TileServer#1]
(Because the cache keys can currently be very large.)

See https://github.com/mojodna/tilelive-cache/commit/92a14eea6a132f6a9b2efbc593d8920edb2fd3b6 for my implementation of a fix using SHA1 hashing of full keys.

**Comment by hanchao** [comment]
Thanks for your report
I have updated [tilelive-cache](https://github.com/mojodna/tilelive-cache)
