### ISSUE TITLE
Can't npm install

### ISSUE THREAD

**Issue by sntiagomoreno** [hanchao/TileServer#2]
I'm new to this environment and I'm getting this error when running npm intall:

mapnik@1.4.15 install: `node-pre-gyp install --fallback-to-build`
 Exit status 1
Failed at the mapnik@1.4.15 install script 'node-pre-gyp install --fallback-to-build'.

Says it is most likely to be a problem with the mapnik package but haven't found any solutions around google.

Thank you!

**Comment by hanchao** [comment]
what OS?

**Comment by hanchao** [comment]
It work on ubuntu 14.04

**Comment by sntiagomoreno** [comment]
Mac OS 10.10.1

**Comment by hanchao** [comment]
I've updated mapnik. It work on OS 10.11, node v4.2.1

**Comment by sntiagomoreno** [comment]
Flawless. Thank you!
